### ISSUE TITLE
Transaction fee added to invoice

### ISSUE THREAD

**Issue by gijs007** [0100Dev/WHMCS-Mollie#49]
It would be great if the Molliegateway module also add's an option to add the payment option fees to the invoice, to make the client pay for these fees.

Some may say there are existing modules which can do this, for example: https://marketplace.whmcs.com/product/2966
This module only allows us to set one global fee for all transactions going through the Mollie gateway. However, since Mollie has several payment options with separate fees the above module can't set the different fees for each payment option. (e.g. ideal is €0,29, Paysafecard is 15%)

Hence why we would need this to be implemented in to the Mollie gateway.

Note:
You may be able to copy this functionality from another WHMCS Mollie payment gateway module, which is no longer actively maintained: https://github.com/peterruiter/whmcs/tree/master/WHMCS%20Mollie

**Comment by Wouter0100** [comment]
This gateway is fundamentally different then the one you're referring to. Those third party add-ons are able to distinguish paysafecard and ideal payments, because of the way this Mollie gateway is designed.

As a result, I stand by my point: it's the job for another add-on to accomplish such features. The gateway is only for handling payments.

**Comment by gijs007** [comment]
Thanks for explaining, my assumption was that all Mollie gateways functioned in the same way (e.g. automatically enabling payment options based on your Mollie settings). 

I'm now a happy user of your payment gateway :)
