### ISSUE TITLE
Plugin not more working. 

### ISSUE THREAD

**Issue by soniXx123** [0100Dev/WHMCS-Mollie#59]
Hi, possible to update the Plugin? this is not more working.

**Comment by thehosting4you** [comment]
What's the problem?

**Comment by soniXx123** [comment]
after copy the files in folder white screen :)

**Comment by thehosting4you** [comment]
Do you have delete the old files

**Comment by soniXx123** [comment]
i dont have old files :) i have a brand new WHMCS setup :)

**Comment by tamerciaga** [comment]
It seems that you need help setting up this gateway module, you can contact the original developer for paid support: www.0100dev.nl ;)

**Comment by Wouter0100** [comment]
Closing the issue for now. Please provide more information if you'd like to get support from the awesome community. Some additional information could be: 
- Install steps you've taken
- Errors you see when debugging the issue.

Otherwise please contact 0100Dev to let them help you with the install, but this is paid.
